# docker-composeのバージョン
version: "3" 

# コンテナ定義
services:
  # webサーバー
  web_ykk08ok:
    # コンテナ名
    container_name: "web_ykk08ok"
    # コンテナの作成に使用するDockerfileのパス
    build:
      dockerfile: "./build/docker/Dockerfile"
    # ホスト側のポート:コンテナ側のポートを指定
    ports:
      - "8883:80"
    # src配下のファイルをコンテナ内の~/va/www/html配下に配置
    volumes:
      - "./:/var/www/html"

  # PHPサーバー
  php_ykk08ok:
    # コンテナ名
    container_name: "php_ykk08ok"
    # コンテナの作成に使用するDockerfileのパス
    build:
      dockerfile: "./build/php/Dockerfile"
    # srcディレクトリ内のファイルをコンテナ内の~/var/www/html配下にマウント
    volumes:
      - "./:/var/www/html"

  # DBサーバー
  db_ykk08ok:
    # コンテナ名
    container_name: "db_ykk08ok"
    # コンテナの作成に使用するDockerfileのパス
    build:
      dockerfile: "./build/db/Dockerfile"
    # ホスト側のポート:コンテナ側のポートを指定
    ports:
      - "3310:3306"
    # 環境変数の指定
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=ykk08ok"
      - "MYSQL_PASSWORD=password"
    # srcディレクトリ内のファイルをコンテナ内の~/var/www/html配下にマウント
    volumes:
      - "./build/db/data:/var/lib/mysql"

